[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio
board_build.arduino.memory_type = opi_opi
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DTFT_TAB_PROFILE=0
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.11.10
  adafruit/Adafruit ST7735 and ST7789 Library @ ^1.11.0
  adafruit/Adafruit BusIO @ ^1.16.1
